name: auto-deploy
on:
  push:
    branches: [master]

jobs:
  archive-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'version.json'
          prop_path: 'version'
      
      - name: get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY.MM.DD
          utcOffset: "+08:00"
      
      - name: action-zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r blinker-esp-idf-${{steps.version.outputs.prop}}.zip . -x .github/* -x .git/*
      
      - name: create json
        id: jsonfile
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "freertos.json"
          json: '{"img": "assets/sdk/freertos.png", "text": "IDF (FreeRTOS)", "update": "${{ steps.current-time.outputs.formattedTime}}", "version": "${{steps.version.outputs.prop}}", "github": "https://github.com/blinker-iot/blinker-esp-idf", "document": "https://diandeng.tech/doc/freertos-support", "download": "sdk/blinker-esp-idf-${{steps.version.outputs.prop}}.zip" }'

      # - name: upload zip
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: blinker-esp-idf-${{steps.version.outputs.prop}}.zip
      #     remote: ${{ secrets.REMOTE_PATH }}/blinker-esp-idf-${{steps.version.outputs.prop}}.zip
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ubuntu
      #     password: ${{ secrets.SERVER_PASSWD }}
      #     recursive: true

      - name: UPload Zip
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ubuntu
          password: ${{secrets.SERVER_PASSWD}}
          port: 22
          uploads: |
            ./ =>  ${{ secrets.REMOTE_PATH }}
          ignore: |
            !blinker-esp-idf-${{steps.version.outputs.prop}}.zip
      
      - name: upload json
        uses: garygrossgarten/github-action-scp@release
        with:
          local: freertos.json
          remote: ${{ secrets.REMOTE_PATH }}/freertos.json
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          password: ${{ secrets.SERVER_PASSWD }}
          recursive: true
